version: "3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "4001:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "4000:8080"
    volumes:
      - ../spec/sub/webapi.yaml:/usr/share/nginx/html/webapi.yaml
    environment:
      API_URL: webapi.yaml
  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "4010:4010"
    command: mock -h 0.0.0.0 /webapi.yaml
    volumes:
      - ../spec/sub/webapi.yaml:/webapi.yaml

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - dynamodb-local-data:/data
    ports:
      - 8000:8000
    # networks:
    #   - tech10_network
    networks:
      - dynamodb-local-network
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    # networks:
    #   - tech10_network
    networks:
      - dynamodb-local-network

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    # networks:
    #   - tech10_network

  moto:
    image: motoserver/moto:latest
    container_name: moto
    ports:
      - "5000:5000"
    environment:
      - MOTO_ACCOUNT_ID=123456789012
    # networks:
    #   - tech10_network

volumes:
  dynamodb-local-data:
networks:
  dynamodb-local-network:
    driver: bridge
# networks:
#   tech10_network:
#     external: true
