service: back
frameworkVersion: '3'

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    define: { 'require.resolve': undefined }
    platform: 'node'
    concurrency: 10
    watch:
      pattern: ['src/**/*.ts'] # match only typescript files in src directory
      ignore: ['temp/**/*']
  dynamodb:
    stages:
      - dev
    start:
      inMemory: true
      port: 8000
      migrate: true
    table:
      - 'memos-${sls:stage}'
    gsi:
      - GSI-General
  serverless-offline:
    httpPort: 3001

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:BatchWriteItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [MemosTable, Arn]
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            # TODO: Fn::GetAtt でGSIを指定する方法が分からない...
            - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamodb.table.0}/index/*'
  environment:
    REGION: ${self:provider.region}
    TABLE_NAME: ${self:custom.dynamodb.table.0}
    GSI1: ${self:custom.dynamodb.gsi.0}

functions:
  app:
    handler: src/handler.handler
    events:
      - http:
          method: ANY
          path: '/'
          cors: true
      - http:
          method: ANY
          path: '/{any+}'
          cors: true

plugins:
  - serverless-esbuild
  - serverless-offline

resources: # CloudFormation template syntax
  Resources:
    MemosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodb.table.0}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: value
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.dynamodb.gsi.0}
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: value
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY
