name: Deploy to AWS

on:
  push:
    branches:
      - main
      - develop
      - ECSITE-39

jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # back.
      - name: Install dependencies(back)
        run: npm ci
        working-directory: app/back

      - name: Run Jest tests and collect coverage
        run: >
          npm run test -- --coverage --maxWorkers=4 --coverageThreshold='{"global": {"branches": 100, "functions": 100, "lines": 100, "statements": 100}}'
        working-directory: app/back

      # - name: Deploy to AWS using Serverless Framework
      #   run: npx serverless deploy
      #   working-directory: app/back
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # # front.
      # - name: Install dependencies(front)
      #   run: npm ci
      #   working-directory: app/front

      # - name: Build
      #   run: npm run build
      #   working-directory: app/front

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: "ap-northeast-1"

      # - name: Empty S3 bucket
      #   run: aws s3 rm s3://${{ vars.AWS_S3_BUCKET_FRONT_DEV }} --recursive

      # - name: Sync files to S3
      #   run: aws s3 sync app/front/out s3://${{ vars.AWS_S3_BUCKET_FRONT_DEV }}/
